---
- name: Log Directories
  file:
    path: "/var/www/{{ item }}/logs"
    owner: vagrant
    group: vagrant
    state: directory
  with_items:
    - gozma14.local
    - www.gozma14.local

- name: Public Html Directory
  copy:
    src: "public_html/gozma14.local/"
    dest: /var/www/gozma14.local/public_html
    owner: vagrant
    group: vagrant

- name: Check Public Html Status for WWW
  stat: path=/var/www/www.gozma14.local/public_html
  register: www_public_html

- name: Public Html Directory (www only)
  copy:
    src: "public_html/www.gozma14.local/"
    dest: /var/www/www.gozma14.local/public_html
    force: no
    owner: vagrant
    group: vagrant
  when: www_public_html.stat.islnk is not defined